tag:
	./bin/tnt -H -v0 models/kannada data/kannada.sample.txt | sed -e 's/\t\+/\t/g' | ./bin/lemmatiser.py models/kannada.lemma > kannada.sample.out.txt 
	#Use option -u1 for quick tagging at the cost of slight precision
